name: Release to PyPI

on:
  release:
    types: [released]

jobs:
  release:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install Tools
      run: |
        python3 -m pip install --user --upgrade setuptools wheel
        python3 -m pip install --user --upgrade twine
    - name: Package and Upload
      env:
        TANGRAM_VERSION: ${{ github.event.release.tag_name }}
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_APIKEY }}
      run: |
        python3 setup.py sdist bdist_wheel
        python3 -m twine upload dist/*

